export interface DocumentItem {
  id: string;
  name: string;
  size: string;
  fileType: 'pdf' | 'docx' | 'txt';
  uploadedAt: string;
  uploadedTimestamp: number; // for sorting
  totalReferences: number;
  validCount: number;
  pendingCount: number;
  failedCount: number;
  status: 'validated' | 'processing' | 'needs_attention';
  isTrash?: boolean;
}

export const MOCK_DOCUMENTS: DocumentItem[] = [
  {
    id: 'DOC-101',
    name: 'Annual_AI_Research_Report_2026.pdf',
    size: '4.2 MB',
    fileType: 'pdf',
    uploadedAt: '10 mins ago',
    uploadedTimestamp: Date.now() - 10 * 60 * 1000,
    totalReferences: 42,
    validCount: 40,
    pendingCount: 2,
    failedCount: 0,
    status: 'needs_attention',
    isTrash: false,
  },
  {
    id: 'DOC-102',
    name: 'Enterprise_Compliance_Doc_v4.docx',
    size: '1.8 MB',
    fileType: 'docx',
    uploadedAt: '45 mins ago',
    uploadedTimestamp: Date.now() - 45 * 60 * 1000,
    totalReferences: 28,
    validCount: 22,
    pendingCount: 5,
    failedCount: 1,
    status: 'needs_attention',
    isTrash: false,
  },
  {
    id: 'DOC-103',
    name: 'Security_Architecture_Blueprint.pdf',
    size: '6.5 MB',
    fileType: 'pdf',
    uploadedAt: '3 hours ago',
    uploadedTimestamp: Date.now() - 3 * 3600 * 1000,
    totalReferences: 64,
    validCount: 64,
    pendingCount: 0,
    failedCount: 0,
    status: 'validated',
    isTrash: false,
  },
  {
    id: 'DOC-104',
    name: 'Medical_Device_Submission_Draft.pdf',
    size: '8.1 MB',
    fileType: 'pdf',
    uploadedAt: 'Yesterday',
    uploadedTimestamp: Date.now() - 24 * 3600 * 1000,
    totalReferences: 53,
    validCount: 45,
    pendingCount: 2,
    failedCount: 6,
    status: 'needs_attention',
    isTrash: false,
  },
  {
    id: 'DOC-105',
    name: 'EU_Market_Compliance_Strategy.pdf',
    size: '2.4 MB',
    fileType: 'pdf',
    uploadedAt: '2 days ago',
    uploadedTimestamp: Date.now() - 48 * 3600 * 1000,
    totalReferences: 31,
    validCount: 29,
    pendingCount: 2,
    failedCount: 0,
    status: 'needs_attention',
    isTrash: false,
  },
  {
    id: 'DOC-106',
    name: 'Smart_Grid_Modernization_Whitepaper.pdf',
    size: '5.0 MB',
    fileType: 'pdf',
    uploadedAt: '4 days ago',
    uploadedTimestamp: Date.now() - 96 * 3600 * 1000,
    totalReferences: 37,
    validCount: 35,
    pendingCount: 0,
    failedCount: 2,
    status: 'needs_attention',
    isTrash: false,
  },
  {
    id: 'DOC-107',
    name: 'HVDC_Substation_Design_Draft.pdf',
    size: '3.9 MB',
    fileType: 'pdf',
    uploadedAt: '1 week ago',
    uploadedTimestamp: Date.now() - 168 * 3600 * 1000,
    totalReferences: 19,
    validCount: 19,
    pendingCount: 0,
    failedCount: 0,
    status: 'validated',
    isTrash: false,
  },
  {
    id: 'DOC-108',
    name: 'Archived_Quarterly_Financial_Risk_Review.docx',
    size: '1.2 MB',
    fileType: 'docx',
    uploadedAt: '2 weeks ago',
    uploadedTimestamp: Date.now() - 336 * 3600 * 1000,
    totalReferences: 15,
    validCount: 12,
    pendingCount: 0,
    failedCount: 3,
    status: 'needs_attention',
    isTrash: true,
  },
  {
    id: 'DOC-109',
    name: 'Deprecated_System_Requirements_Spec.txt',
    size: '450 KB',
    fileType: 'txt',
    uploadedAt: '3 weeks ago',
    uploadedTimestamp: Date.now() - 504 * 3600 * 1000,
    totalReferences: 8,
    validCount: 6,
    pendingCount: 0,
    failedCount: 2,
    status: 'needs_attention',
    isTrash: true,
  },
];
