export interface ReferenceItem {
  id: string;
  citation: string;
  sourceDoc: string;
  doiOrUrl?: string;
  status: 'valid' | 'pending' | 'failed';
  matchedConfidence: number; // e.g. 98%
  publicationYear?: number;
  authors?: string;
  journalOrPublisher?: string;
  issueDetails?: string;
  validatedAt: string;
  category: 'journal' | 'standard' | 'report' | 'book' | 'web';
}

export const MOCK_REFERENCES: ReferenceItem[] = [
  {
    id: 'REF-8921',
    citation: 'He, K., Zhang, X., Ren, S., & Sun, J. (2016). Deep Residual Learning for Image Recognition. Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 770-778.',
    sourceDoc: 'Annual_AI_Research_Report_2026.pdf',
    doiOrUrl: 'https://doi.org/10.1109/CVPR.2016.90',
    status: 'valid',
    matchedConfidence: 99,
    publicationYear: 2016,
    authors: 'K. He, X. Zhang, S. Ren, J. Sun',
    journalOrPublisher: 'IEEE CVPR',
    validatedAt: '10 mins ago',
    category: 'journal',
  },
  {
    id: 'REF-8920',
    citation: 'ISO/IEC 27001:2022 Information security, cybersecurity and privacy protection — Information security management systems — Requirements.',
    sourceDoc: 'Enterprise_Compliance_Doc_v4.docx',
    doiOrUrl: 'https://www.iso.org/standard/27001',
    status: 'pending',
    matchedConfidence: 74,
    publicationYear: 2022,
    authors: 'ISO/IEC JTC 1/SC 27',
    journalOrPublisher: 'International Organization for Standardization',
    issueDetails: 'Edition 3 revision metadata pending manual verification against ISO catalogue.',
    validatedAt: '35 mins ago',
    category: 'standard',
  },
  {
    id: 'REF-8919',
    citation: 'NIST Special Publication 800-53 Rev. 5: Security and Privacy Controls for Information Systems and Organizations.',
    sourceDoc: 'Security_Architecture_Blueprint.pdf',
    doiOrUrl: 'https://doi.org/10.6028/NIST.SP.800-53r5',
    status: 'valid',
    matchedConfidence: 98,
    publicationYear: 2020,
    authors: 'Joint Task Force',
    journalOrPublisher: 'National Institute of Standards and Technology',
    validatedAt: '2 hours ago',
    category: 'standard',
  },
  {
    id: 'REF-8918',
    citation: 'WHO Technical Report Series No. 986 - Annex 2: WHO good manufacturing practices for pharmaceutical products: main principles.',
    sourceDoc: 'Medical_Device_Submission_Draft.pdf',
    doiOrUrl: 'https://apps.who.int/iris/handle/10665/129719',
    status: 'failed',
    matchedConfidence: 41,
    publicationYear: 2014,
    authors: 'World Health Organization',
    journalOrPublisher: 'WHO Guidelines Approved by the Guidelines Review Committee',
    issueDetails: 'Permanent redirect loop detected on Iris repository; citation link broken (HTTP 404).',
    validatedAt: 'Yesterday',
    category: 'report',
  },
  {
    id: 'REF-8917',
    citation: 'Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A. N., Kaiser, Ł., & Polosukhin, I. (2017). Attention Is All You Need. Advances in Neural Information Processing Systems (NeurIPS), 30, 5998–6008.',
    sourceDoc: 'Annual_AI_Research_Report_2026.pdf',
    doiOrUrl: 'https://arxiv.org/abs/1706.03762',
    status: 'valid',
    matchedConfidence: 100,
    publicationYear: 2017,
    authors: 'A. Vaswani et al.',
    journalOrPublisher: 'NeurIPS 2017',
    validatedAt: '1 day ago',
    category: 'journal',
  },
  {
    id: 'REF-8916',
    citation: 'European Commission (2024). Regulation (EU) 2024/1689 laying down harmonised rules on artificial intelligence (Artificial Intelligence Act).',
    sourceDoc: 'EU_Market_Compliance_Strategy.pdf',
    doiOrUrl: 'http://data.europa.eu/eli/reg/2024/1689/oj',
    status: 'pending',
    matchedConfidence: 82,
    publicationYear: 2024,
    authors: 'European Parliament and Council of the European Union',
    journalOrPublisher: 'Official Journal of the European Union',
    issueDetails: 'New consolidated version amendment requires ratification comparison.',
    validatedAt: '2 days ago',
    category: 'standard',
  },
  {
    id: 'REF-8915',
    citation: 'Smith, J. A., & Doe, R. B. (2019). Quantum Cryptographic Protocols in Distributed Power Grids. IEEE Transactions on Smart Grid, 10(4), 4120-4129.',
    sourceDoc: 'Smart_Grid_Modernization_Whitepaper.pdf',
    doiOrUrl: 'https://doi.org/10.1109/TSG.2019.0041201',
    status: 'failed',
    matchedConfidence: 35,
    publicationYear: 2019,
    authors: 'J. A. Smith, R. B. Doe',
    journalOrPublisher: 'IEEE Transactions on Smart Grid',
    issueDetails: 'DOI not found in CrossRef database. Possible typo in volume index (vol 10 issue 4).',
    validatedAt: '3 days ago',
    category: 'journal',
  },
  {
    id: 'REF-8914',
    citation: 'IEEE 1547-2018: IEEE Standard for Interconnection and Interoperability of Distributed Energy Resources with Associated Electric Power Systems Interfaces.',
    sourceDoc: 'Renewable_Integration_Specs_v2.pdf',
    doiOrUrl: 'https://standards.ieee.org/ieee/1547/5847/',
    status: 'valid',
    matchedConfidence: 96,
    publicationYear: 2018,
    authors: 'IEEE Standards Association',
    journalOrPublisher: 'IEEE',
    validatedAt: '4 days ago',
    category: 'standard',
  },
  {
    id: 'REF-8913',
    citation: 'World Energy Outlook 2025: Transition Pathways and Grid Resilience Analysis. International Energy Agency (IEA).',
    sourceDoc: 'Global_Energy_Forecast_2026.pdf',
    doiOrUrl: 'https://www.iea.org/reports/world-energy-outlook-2025',
    status: 'pending',
    matchedConfidence: 79,
    publicationYear: 2025,
    authors: 'International Energy Agency',
    journalOrPublisher: 'IEA Publications',
    issueDetails: 'Citation points to embargoed preview page; public DOI resolver has changed.',
    validatedAt: '5 days ago',
    category: 'report',
  },
  {
    id: 'REF-8912',
    citation: 'Chen, L., Wang, Y., & Zhang, T. (2023). High-Voltage Direct Current (HVDC) Transmission Efficiency Benchmarks in Renewable Substations. Energy Reports, 9, 1205-1218.',
    sourceDoc: 'HVDC_Substation_Design_Draft.pdf',
    doiOrUrl: 'https://doi.org/10.1016/j.egyr.2023.01.112',
    status: 'valid',
    matchedConfidence: 95,
    publicationYear: 2023,
    authors: 'L. Chen, Y. Wang, T. Zhang',
    journalOrPublisher: 'Energy Reports (Elsevier)',
    validatedAt: '1 week ago',
    category: 'journal',
  },
];
